apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config-1
  namespace: dev

data:
  DATABASE_URL: "mysql://testuser1:testpass1@mysql-server:3306/testdb1"
  API_KEY: "test-api-key-1"
  LOG_LEVEL: "info"
  FEATURE_FLAG: "true"
